export const demoClients = [
  {
    id: 1,
    fullName: 'Alice Montgomery',
    phone: '+1 (555) 123-4567',
    email: 'alice@example.com',
    city: 'San Francisco, CA',
    matter: 'Real Estate Litigation',
    status: 'In Progress',
    notes:
      'Client reviewed the proposed retainer agreement. Focused on the IP litigation strategy for the upcoming fiscal quarter.',
    address: '1200 California St, San Francisco',
    retainerBalance: '$12,450.00',
    hoursBilled: '42.5 hrs',
    lastPayment: '2026-07-02T00:00:00.000Z',
    createdAt: '2026-07-01T11:20:00.000Z',
    updatedAt: '2026-07-08T14:15:00.000Z',
    documents: [
      { id: 1, name: 'Retainer_Agreement_V2.pdf', size: '4.2 MB', updatedLabel: 'Updated 2 days ago' },
      { id: 2, name: 'Initial_Case_Strategy.docx', size: '1.1 MB', updatedLabel: 'Updated 5 days ago' },
    ],
    activities: [
      {
        id: 1,
        title: 'Note added: Initial consultation complete',
        details:
          'Client reviewed the proposed retainer agreement. Next step: internal case review.',
        occurredAt: '2026-07-08T14:15:00.000Z',
      },
      {
        id: 2,
        title: 'Status changed to In Progress',
        details: 'Transitioned from Lead to Active Client after deposit confirmation.',
        occurredAt: '2026-07-05T09:45:00.000Z',
      },
      {
        id: 3,
        title: 'Client created',
        details: 'Record initialized via website inquiry form.',
        occurredAt: '2026-07-01T11:20:00.000Z',
      },
    ],
  },
  {
    id: 2,
    fullName: 'Benjamin Harrison',
    phone: '+1 (555) 987-6543',
    email: 'benjamin@example.com',
    city: 'Chicago, IL',
    matter: 'Corporate Fraud Defense',
    status: 'In Progress',
    notes: 'High-priority compliance review scheduled with internal audit team.',
    createdAt: '2026-06-23T08:00:00.000Z',
    updatedAt: '2026-07-07T09:10:00.000Z',
    activities: [],
    documents: [],
  },
  {
    id: 3,
    fullName: 'Catherine Kim',
    phone: '+1 (555) 444-2222',
    email: 'catherine@example.com',
    city: 'Seattle, WA',
    matter: 'Family Law / Mediation',
    status: 'Closed',
    notes: 'Final settlement package signed and archived.',
    createdAt: '2026-05-18T10:00:00.000Z',
    updatedAt: '2026-07-03T16:30:00.000Z',
    activities: [],
    documents: [],
  },
  {
    id: 4,
    fullName: 'David Sinclair',
    phone: '+1 (555) 888-0099',
    email: 'david@example.com',
    city: 'Austin, TX',
    matter: 'Intellectual Property',
    status: 'New',
    notes: 'Waiting for conflict check and initial documentation.',
    createdAt: '2026-07-09T08:45:00.000Z',
    updatedAt: '2026-07-09T08:45:00.000Z',
    activities: [],
    documents: [],
  },
]

export const demoSettings = {
  profile: {
    firmName: 'Jenkins & Associates',
    lawyerName: 'Sarah Jenkins',
    email: 's.jenkins@jenkins-law.com',
    phone: '+1 (555) 234-5678',
  },
  notifications: {
    email: true,
    telegram: false,
    desktop: true,
  },
  preferences: {
    language: 'en-US',
    theme: 'light',
  },
}
